### ISSUE TITLE
Non-Required Fields Populated With Unreasonable Defaults

### ISSUE THREAD

**Issue by thenadz** [WSDOT/wzdx.models#4]
In contrasting the spec with this library's behavior, a number of fields are being populated with a default value even though they are not required. Below is a partial list of examples I've identified.

- `road_event_feed_info/data_sources/update_frequency`
- `feature/properties/beginning_milepost`
- `feature/properties/ending_milepost`
- `feature/properties/core_details/update_date`

**Comment by rhuebner76** [comment]
@thenadz thanks, I will look into these, schema generator tools probably missed what should have been a nullable property.

**Comment by thenadz** [comment]
Awesome - thx!

**Comment by rhuebner76** [comment]
@thenadz refactored to allow null values for primitive data types and structures where applicable. Please check the latest (v0.0.6). Thanks. If you see any more feel free to share.

**Comment by rhuebner76** [comment]
@thenadz see latest release v0.0.6 for changes to the immutability of the builders.

**Comment by thenadz** [comment]
Thanks! Confirmed.
