### ISSUE TITLE
Optional Milepost Parameters Incorrectly Populated with Default

### ISSUE THREAD

**Issue by thenadz** [WSDOT/wzdx.models#5]
Following up to #4, it looks like feature mileposts are still being set to non-null 0 as default even though the field is not required per the [spec](https://github.com/usdot-jpo-ode/wzdx/blob/main/schemas/4.0/RoadEventFeature.json#L155). Both `beginning_milepost` and `ending_milepost` impactd.

**Comment by jhudsonWA** [comment]
Due to some vacations/staffing changes, it may take a bit longer to get this fixed than before. If you have a PR would love to consider it next week.

**Comment by thenadz** [comment]
Hi @jhudsonWA - No problem at all. Thanks for the heads up. Yes, I'll plan to get a PR together for this.
