### ISSUE TITLE
License for this codebase & published Nuget packages

### ISSUE THREAD

**Issue by thenadz** [WSDOT/wzdx.models#7]
To ease any concerns by folks looking to use this library, would it be possible to add a license file to the codebase and to the nuget packages being published?

In keeping with USDOT's license for the feed contents generated by this library, I humbly propose [CC0](https://creativecommons.org/publicdomain/zero/1.0/) as a logical fit if this is acceptable?

**Comment by jhudsonWA** [comment]
Thinking this one over. More soon. CC0 seems promising but want to make sure.

**Comment by jhudsonWA** [comment]
After internal discussions, we should be able to do CC0 but we will probably rename the namespace and library to just be wzdx.models. This change feels like it is a better fit for open source and public domain concepts. Give us a few days to make those changes.

**Comment by thenadz** [comment]
This is great news!! Thanks - this will be great in fostering broader adoption of this fantastic library!

**Comment by jhudsonWA** [comment]
I was able to dive in and make the changes. This is now released as 0.0.8

Namespace goes from wzdot.wzdx.models to wzdx.models.

Can't rename a NUGET package so all previous versions are deprecated and point to the new home: https://www.nuget.org/packages/Wzdx.Models/

The CC0 license is now part of the package.
