### ISSUE TITLE
WorkZoneRoadEventFeatureBuilder Question

### ISSUE THREAD

**Issue by PabloCruise2022** [WSDOT/wzdx.models#8]
This isn't issue - it's a question.  And I'm new to GitHub and couldn't figure out how to send a question.

I'm creating a WZDx v4 feed for ODOT using your individual builders to create the feed objects.  

From the input file I have a geometry string for each feature. I'm trying to add the geometry to the feature in the output file via the featureBuilder.WithGeometry method.  I having trouble figuring out how to convert strings that contain MultPoint or LineString data into the object needed by the call.

In the example on your website you show this:
_featureBuilder.WithGeometry(MultiPoint.FromCoordinates(new[] { Position.From(0, 0), Position.From(10, 10) }));_

How would I pass in an container of values in either MultPoint or LineString format?

Do you have any examples?

MultiPoint and LineString strings can vary - for instance:
<geometry_coordinates>POINT (-13810127.935382422 5562522.5054757064)</geometry_coordinates>
<geometry_coordinates>POINT (-13485006.004181771 5717295.2580304639), POINT (-13485058.324342443 5717010.4397202637)</geometry_coordinates>
    <geometry_coordinates>LINESTRING (-13691006.0614794 5608225.34169829, -13691120.720555 5608770.83458318, -13691185.2858596 5609258.1903829, -13691197.5310036 5610759.72598123)</geometry_coordinates>
	Line  98:       <geometry_coordinates>LINESTRING (-13691006.0614794 5608225.34169829, -13691120.720555 5608770.83458318, -13691185.2858596 5609258.1903829, -13691197.5310036 5610759.72598123, -13691185.2860000 5609258.1900000, -13691197.5310000 5610759.72590000)</geometry_coordinates>

It looks like it needs a _MultiPoint.FromCoordinates(IEnumerable<IPosition> value_) which I guess is an collection of IPosition values.  However, when I try to create an IPosition value it says I can't set it - it is read only.   

Sorry but I have very little experience dealing with Interface objects.

Thanks in advance!

**Comment by rhuebner76** [comment]
@PabloCruise2022 there are a few ways to create an instance of IPosition.

Hopefully this helps, yet if you have any other questions or need help I do not mind helping out. Yes, to create a geometry object here the easiest way is use one of the factory methods and instantiate a new instance of the IPosition interface using the Position class.

``` cs
// constructor
      IPosition position = new Position(longitude, latitude);
```
``` cs
// factory method
      IPosition position = Position.From(new [] { longitude, latitude } );
```

Moreover, there are several ways to make this work. From your example you would need to read and parse the geometry string from your XML elements, and then convert the geometry string to a geometry object (e.g., IGeometry). Just for fun I wrote a small method to convert from your string into an instance of IGeometry.

``` cs
      private static IGeometry GeometryFrom(string value)
      {
          const string typeGroup = "type";
          const string coordinateGroup = "coordinates";

          var regex = new Regex($"(?<{typeGroup}>\\w*)\\s\\((?<{coordinateGroup}>.*)\\)");
          var match = regex.Matches(value);

          var groups = match[0].Groups;
          var type = groups[typeGroup].ToString().ToUpper();
          var positions = groups[coordinateGroup].ToString()
              .Split(',')
              .Select(pair => (IPosition)Position.From(pair.Trim().Split(" ").Select(double.Parse)))
              .ToList()
              .AsReadOnly();

          switch (type)
          {
              case "POINT":
                  var position = positions.Single();
                  return GeometryFactory.CreatePoint(position.Longitude, position.Latitude);
              case "LINESTRING":
                  return GeometryFactory.CreateLineString(positions);
              case "MULTIPOINT":
                  return GeometryFactory.CreateMultiPoint(positions);
          }

          return GeometryFactory.CreateNull();
      }
```
As a note, Position.From probably should return an instance of IPosition not Position itself.

**Comment by PabloCruise2022** [comment]
Russ,

Thanks for the quick response.  I’ll give it a try later today.

All the other builders work great.  But the Geometry threw me for a loop.  I figured it was something similar.

Thanks,
Paul

**Comment by PabloCruise2022** [comment]
Russ,

I’m able to use the GeometryFrom method with LINESTRING coordinates.  However I’m having trouble with the MULTIPOINT strings.

Can you give me example of what format does it expect the MULTIPOINT string to be in?

Would it be something like this: “MULTIPOINT (-13485006.004181771 5717295.2580304639), (-13485058.324342443 5717010.4397202637)”

Thanks,
Paul

**Comment by PabloCruise2022** [comment]
Russ,

Never mind.  I think I figured it out.  This seems to work:

MULTIPOINT (-13485006.004181771 5717295.2580304639, -13485058.324342443 5717010.4397202637)

Thanks,
Paul

**Comment by PabloCruise2022** [comment]
Russ,

I’m trying to use the WithLane method on a featurebuilder.  The last parameter is asking for function.   I’m confused on what I should pass it.

Do you have an example?

***@***.***

Thanks,
Paul

**Comment by rhuebner76** [comment]
@PabloCruise2022, the last parameter in the WithLane method is a configuration delegate that allows for using the sub-builder. The builders are designed to set the defaults, ensuring that the resulting object is schema compliant. There are additional options for some, if not most, that are accessible through the configuration delegate. 

The simplest usage
``` csharp
builder => builder.WithLane(LaneType.BikeLane, LaneStatus.Closed, 0, laneBuilder => laneBuilder),
```

In the lane builder allows for building restrictions for the lane. 

``` csharp
builder => builder.WithLane(LaneType.BikeLane, LaneStatus.Closed, 0, 
                    laneBuilder => laneBuilder.WithNoRestrictions())
```

``` csharp
builder => builder.WithLane(LaneType.BikeLane, LaneStatus.Closed, 0, 
                    laneBuilder => laneBuilder.WithRestriction(RestrictionType.AxleLoadLimit, UnitOfMeasurement.Centimeters, restrictionBuilder => restrictionBuilder)),
```

**Comment by rhuebner76** [comment]
Seems the issue has been resolved.
