### ISSUE TITLE
Add Support for WZDx 4.1

### ISSUE THREAD

**Issue by thenadz** [WSDOT/wzdx.models#9]
With the [release of WZDx 4.1](https://github.com/usdot-jpo-ode/wzdx/commit/5952f210026c091bca1e4082c0c4e43cf16eb519), would be great to get support for this new version here.

**Comment by jhudsonWA** [comment]
We agree and will be working on it. :)

**Comment by thenadz** [comment]
Amazing!! Really appreciate all the work going into making this a useful tool for rapid WZDx adoption!

**Comment by jhudsonWA** [comment]
This work has been merged in, creating a nugget package update now. We simply updated 4 to 4.1. There are a few deprecated fields, but it should not be breaking.
